/*
 * PEPView.java
 */

package pep;

import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.TaskMonitor;
import org.jdesktop.application.FrameView;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.KeyStroke;
import pepCalculator.Norm;

/**
 * The application's main frame.
 */
public class PEPView extends FrameView {

    public PEPView(SingleFrameApplication app) {
        super(app);

        initCalcs();
        initComponents();

        // status bar initialization - message timeout, idle icon and busy animation, etc
        ResourceMap resourceMap = getResourceMap();
        int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
        messageTimer = new Timer(messageTimeout, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                //statusMessageLabel.setText("");
            }
        });
        messageTimer.setRepeats(false);
        int busyAnimationRate = resourceMap.getInteger("StatusBar.busyAnimationRate");
        for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = resourceMap.getIcon("StatusBar.busyIcons[" + i + "]");
        }
        busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
                //statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
            }
        });
        idleIcon = resourceMap.getIcon("StatusBar.idleIcon");
        //statusAnimationLabel.setIcon(idleIcon);
        //progressBar.setVisible(false);

        // connecting action tasks to status bar via TaskMonitor
        TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                if ("started".equals(propertyName)) {
                    if (!busyIconTimer.isRunning()) {
                        //statusAnimationLabel.setIcon(busyIcons[0]);
                        busyIconIndex = 0;
                        busyIconTimer.start();
                    }
                    //progressBar.setVisible(true);
                    //progressBar.setIndeterminate(true);
                } else if ("done".equals(propertyName)) {
                    busyIconTimer.stop();
                    //statusAnimationLabel.setIcon(idleIcon);
                    //progressBar.setVisible(false);
                    //progressBar.setValue(0);
                } else if ("message".equals(propertyName)) {
                    String text = (String)(evt.getNewValue());
                    //statusMessageLabel.setText((text == null) ? "" : text);
                    messageTimer.restart();
                } else if ("progress".equals(propertyName)) {
                    int value = (Integer)(evt.getNewValue());
                    //progressBar.setVisible(true);
                    //progressBar.setIndeterminate(false);
                    //progressBar.setValue(value);
                }
            }
        });

        getFrame().setResizable(false);
        //getFrame().setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        loadDefaultParamFile();
        reflectCalcs();
    }

    @Action
    public void saveDefaultParamFile() {
        int idx = calculatorsTPane.getSelectedIndex();
        
        if (idx == 0)
        {
            cewkaCalc.SaveDefaultCfg();
        }
        else if (idx == 1)
        {
            LPNCalc.LoadDefaultCfg();
        }
    }
    
    public void loadDefaultParamFile() {
        int idx = calculatorsTPane.getSelectedIndex();
        
        if (idx == 0)
        {
            cewkaCalc.LoadDefaultCfg();
        }
        else if (idx == 1)
        {
            ;
        }
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = PEPApp.getApplication().getMainFrame();
            aboutBox = new PEPAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        PEPApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        calculatorsTPane = new javax.swing.JTabbedPane();
        cewkapPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanelCewkaWe = new javax.swing.JPanel();
        jSpinnerCewkaX = new javax.swing.JSpinner();
        jSpinnerCewkaD = new javax.swing.JSpinner();
        jSpinnerCewkaN = new javax.swing.JSpinner();
        jLabelCewkaX = new javax.swing.JLabel();
        jLabelCewkaD = new javax.swing.JLabel();
        jLabelCewkaN = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelCewkaMaxSr = new javax.swing.JLabel();
        jLabelCewkaDDivX = new javax.swing.JLabel();
        jLabelCewkaRs = new javax.swing.JLabel();
        jLabelCewkaXJdn = new javax.swing.JLabel();
        jLabelCewkaDJdn = new javax.swing.JLabel();
        jLabelCewkaNJdn = new javax.swing.JLabel();
        jTextCewkaRs = new javax.swing.JTextField();
        jLabelCewkaRsJdn = new javax.swing.JLabel();
        jPanelCewkaWy = new javax.swing.JPanel();
        jLabelCewkaL = new javax.swing.JLabel();
        jLabelCewkaLMi = new javax.swing.JLabel();
        jLabelCewkaQl = new javax.swing.JLabel();
        jPanelCewkaParam = new javax.swing.JPanel();
        jLabelCewkaUw = new javax.swing.JLabel();
        jLabelCewkaFx = new javax.swing.JLabel();
        jLabelCewkaWzor = new javax.swing.JLabel();
        jSpinnerCewkaFx = new javax.swing.JSpinner();
        jLabelCewkaFxJdn = new javax.swing.JLabel();
        jTextCewkaMi = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        lpnPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanelLPNWe = new javax.swing.JPanel();
        jLabelLPNW = new javax.swing.JLabel();
        jLabelLPNH = new javax.swing.JLabel();
        jSpinnerLPNW = new javax.swing.JSpinner();
        jSpinnerLPNH = new javax.swing.JSpinner();
        jSeparator3 = new javax.swing.JSeparator();
        jLabelLPNWJdn = new javax.swing.JLabel();
        jLabelLPNHJdn = new javax.swing.JLabel();
        jLabelLPNWDivH = new javax.swing.JLabel();
        jLabelLPNW_ef = new javax.swing.JLabel();
        jLabelLPNEps_ef = new javax.swing.JLabel();
        jLabelLPNW_mls = new javax.swing.JLabel();
        jLabelLPNW_mlsJdn = new javax.swing.JLabel();
        jPanelLPNWy = new javax.swing.JPanel();
        jLabelLPNZ0 = new javax.swing.JLabel();
        jPanelLPNParam = new javax.swing.JPanel();
        jLabelLPNT = new javax.swing.JLabel();
        jLabelLPNEps = new javax.swing.JLabel();
        jTextLPNT = new javax.swing.JTextField();
        jSpinnerLPNEps = new javax.swing.JSpinner();
        jLabelLPNTJdn = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        rezPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanelRezonWe = new javax.swing.JPanel();
        jPanelRezonWy = new javax.swing.JPanel();
        jPanelRezonParam = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        jMenuItemOtworz = new javax.swing.JMenuItem();
        jMenuItemZapisz = new javax.swing.JMenuItem();
        jMenuItemZapiszJako = new javax.swing.JMenuItem();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();

        mainPanel.setName("mainPanel"); // NOI18N

        calculatorsTPane.setFont(calculatorsTPane.getFont().deriveFont(calculatorsTPane.getFont().getSize()+1f));
        calculatorsTPane.setName("calculatorsTPane"); // NOI18N

        cewkapPanel.setName("cewkapPanel"); // NOI18N

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getSize()+3f));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(pep.PEPApp.class).getContext().getResourceMap(PEPView.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel4.setFont(jLabel4.getFont());
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel7.setFont(jLabel7.getFont().deriveFont(jLabel7.getFont().getSize()+1f));
        jLabel7.setForeground(resourceMap.getColor("jLabel7.foreground")); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setFont(jLabel8.getFont());
        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel9.setFont(jLabel9.getFont());
        jLabel9.setForeground(resourceMap.getColor("jLabel9.foreground")); // NOI18N
        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        jPanelCewkaWe.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), resourceMap.getString("jPanelCewkaWe.border.title"), 0, 0, resourceMap.getFont("jPanelCewkaWe.border.titleFont"), resourceMap.getColor("jPanelCewkaWe.border.titleColor"))); // NOI18N
        jPanelCewkaWe.setForeground(resourceMap.getColor("jPanelCewkaWe.foreground")); // NOI18N
        jPanelCewkaWe.setFont(jPanelCewkaWe.getFont().deriveFont(jPanelCewkaWe.getFont().getStyle() | java.awt.Font.BOLD, jPanelCewkaWe.getFont().getSize()+1));
        jPanelCewkaWe.setName("jPanelCewkaWe"); // NOI18N

        jSpinnerCewkaX.setModel(new StepCountingSpinnerNumberModel());
        jSpinnerCewkaX.setEditor(new ModelIndependentSpinnerEditor(jSpinnerCewkaX));
        jSpinnerCewkaX.setName("jSpinnerCewkaX"); // NOI18N
        ((ModelIndependentSpinnerEditor)jSpinnerCewkaX.getEditor()).getTextField().
        addActionListener(new ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cewkaXEditActionPerformed(evt);
            }
        });

        jSpinnerCewkaX.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(javax.swing.KeyStroke.getKeyStroke("F1"), "F1 pressed");
        jSpinnerCewkaX.getActionMap().put("F1 pressed", new javax.swing.AbstractAction() {
            public void actionPerformed(ActionEvent evt) {
                cewkaCalc.decX(false);
                ReflectCewkaCalc();
            }
        });

        jSpinnerCewkaX.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(javax.swing.KeyStroke.getKeyStroke("shift F1"), "shift F1 pressed");
        jSpinnerCewkaX.getActionMap().put("shift F1 pressed", new javax.swing.AbstractAction() {
            public void actionPerformed(ActionEvent evt) {
                cewkaCalc.decX(true);
                ReflectCewkaCalc();
            }
        });

        jSpinnerCewkaX.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(javax.swing.KeyStroke.getKeyStroke("F2"), "F2 pressed");
        jSpinnerCewkaX.getActionMap().put("F2 pressed", new javax.swing.AbstractAction() {
            public void actionPerformed(ActionEvent evt) {
                cewkaCalc.incX(false);
                ReflectCewkaCalc();
            }
        });

        jSpinnerCewkaX.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(javax.swing.KeyStroke.getKeyStroke("shift F2"), "shift F2 pressed");
        jSpinnerCewkaX.getActionMap().put("shift F2 pressed", new javax.swing.AbstractAction() {
            public void actionPerformed(ActionEvent evt) {
                cewkaCalc.incX(true);
                ReflectCewkaCalc();
            }
        });
        jSpinnerCewkaX.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerCewkaXStateChanged(evt);
            }
        });

        jSpinnerCewkaD.setModel(new StepCountingSpinnerNumberModel());
        jSpinnerCewkaD.setEditor(new ModelIndependentSpinnerEditor(jSpinnerCewkaD));
        jSpinnerCewkaD.setName("jSpinnerCewkaD"); // NOI18N
        ((ModelIndependentSpinnerEditor)jSpinnerCewkaD.getEditor()).getTextField().
        addActionListener(new ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cewkaDEditActionPerformed(evt);
            }
        });

        jSpinnerCewkaD.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(javax.swing.KeyStroke.getKeyStroke("F3"), "F3 pressed");
        jSpinnerCewkaD.getActionMap().put("F3 pressed", new javax.swing.AbstractAction() {
            public void actionPerformed(ActionEvent evt) {
                cewkaCalc.decD(false);
                ReflectCewkaCalc();
            }
        });

        jSpinnerCewkaD.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(javax.swing.KeyStroke.getKeyStroke("shift F3"), "shift F3 pressed");
        jSpinnerCewkaD.getActionMap().put("shift F3 pressed", new javax.swing.AbstractAction() {
            public void actionPerformed(ActionEvent evt) {
                cewkaCalc.decD(true);
                ReflectCewkaCalc();
            }
        });

        jSpinnerCewkaD.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(javax.swing.KeyStroke.getKeyStroke("F4"), "F4 pressed");
        jSpinnerCewkaD.getActionMap().put("F4 pressed", new javax.swing.AbstractAction() {
            public void actionPerformed(ActionEvent evt) {
                cewkaCalc.incD(false);
                ReflectCewkaCalc();
            }
        });

        jSpinnerCewkaD.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(javax.swing.KeyStroke.getKeyStroke("shift F4"), "shift F4 pressed");
        jSpinnerCewkaD.getActionMap().put("shift F4 pressed", new javax.swing.AbstractAction() {
            public void actionPerformed(ActionEvent evt) {
                cewkaCalc.incD(true);
                ReflectCewkaCalc();
            }
        });
        jSpinnerCewkaD.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerCewkaDStateChanged(evt);
            }
        });

        jSpinnerCewkaN.setModel(new StepCountingSpinnerNumberModel());
        jSpinnerCewkaN.setEditor(new ModelIndependentSpinnerEditor(jSpinnerCewkaN));
        jSpinnerCewkaN.setName("jSpinnerCewkaN"); // NOI18N
        ((ModelIndependentSpinnerEditor)jSpinnerCewkaN.getEditor()).getTextField().
        addActionListener(new ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cewkaNEditActionPerformed(evt);
            }
        });

        jSpinnerCewkaN.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(javax.swing.KeyStroke.getKeyStroke("F5"), "F5 pressed");
        jSpinnerCewkaN.getActionMap().put("F5 pressed", new javax.swing.AbstractAction() {
            public void actionPerformed(ActionEvent evt) {
                cewkaCalc.decN(false);
                ReflectCewkaCalc();
            }
        });

        jSpinnerCewkaN.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(javax.swing.KeyStroke.getKeyStroke("shift F5"), "shift F5 pressed");
        jSpinnerCewkaN.getActionMap().put("shift F5 pressed", new javax.swing.AbstractAction() {
            public void actionPerformed(ActionEvent evt) {
                cewkaCalc.decN(true);
                ReflectCewkaCalc();
            }
        });

        jSpinnerCewkaN.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(javax.swing.KeyStroke.getKeyStroke("F6"), "F6 pressed");
        jSpinnerCewkaN.getActionMap().put("F6 pressed", new javax.swing.AbstractAction() {
            public void actionPerformed(ActionEvent evt) {
                cewkaCalc.incN(false);
                ReflectCewkaCalc();
            }
        });

        jSpinnerCewkaN.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(javax.swing.KeyStroke.getKeyStroke("shift F6"), "shift F6 pressed");
        jSpinnerCewkaN.getActionMap().put("shift F6 pressed", new javax.swing.AbstractAction() {
            public void actionPerformed(ActionEvent evt) {
                cewkaCalc.incN(true);
                ReflectCewkaCalc();
            }
        });
        jSpinnerCewkaN.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerCewkaNStateChanged(evt);
            }
        });

        jLabelCewkaX.setFont(jLabelCewkaX.getFont().deriveFont(jLabelCewkaX.getFont().getStyle() | java.awt.Font.BOLD));
        jLabelCewkaX.setText(resourceMap.getString("jLabelCewkaX.text")); // NOI18N
        jLabelCewkaX.setName("jLabelCewkaX"); // NOI18N

        jLabelCewkaD.setFont(jLabelCewkaD.getFont().deriveFont(jLabelCewkaD.getFont().getStyle() | java.awt.Font.BOLD));
        jLabelCewkaD.setText(resourceMap.getString("jLabelCewkaD.text")); // NOI18N
        jLabelCewkaD.setName("jLabelCewkaD"); // NOI18N

        jLabelCewkaN.setFont(jLabelCewkaN.getFont().deriveFont(jLabelCewkaN.getFont().getStyle() | java.awt.Font.BOLD));
        jLabelCewkaN.setText(resourceMap.getString("jLabelCewkaN.text")); // NOI18N
        jLabelCewkaN.setName("jLabelCewkaN"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        jLabelCewkaMaxSr.setFont(jLabelCewkaMaxSr.getFont().deriveFont(jLabelCewkaMaxSr.getFont().getStyle() | java.awt.Font.BOLD));
        jLabelCewkaMaxSr.setText(resourceMap.getString("jLabelCewkaMaxSr.text")); // NOI18N
        jLabelCewkaMaxSr.setName("jLabelCewkaMaxSr"); // NOI18N

        jLabelCewkaDDivX.setFont(jLabelCewkaDDivX.getFont().deriveFont(jLabelCewkaDDivX.getFont().getStyle() | java.awt.Font.BOLD));
        jLabelCewkaDDivX.setText(resourceMap.getString("jLabelCewkaDDivX.text")); // NOI18N
        jLabelCewkaDDivX.setName("jLabelCewkaDDivX"); // NOI18N

        jLabelCewkaRs.setFont(jLabelCewkaRs.getFont().deriveFont(jLabelCewkaRs.getFont().getStyle() | java.awt.Font.BOLD));
        jLabelCewkaRs.setText(resourceMap.getString("jLabelCewkaRs.text")); // NOI18N
        jLabelCewkaRs.setName("jLabelCewkaRs"); // NOI18N

        jLabelCewkaXJdn.setFont(jLabelCewkaXJdn.getFont().deriveFont(jLabelCewkaXJdn.getFont().getStyle() | java.awt.Font.BOLD));
        jLabelCewkaXJdn.setText(resourceMap.getString("jLabelCewkaXJdn.text")); // NOI18N
        jLabelCewkaXJdn.setName("jLabelCewkaXJdn"); // NOI18N

        jLabelCewkaDJdn.setFont(jLabelCewkaDJdn.getFont().deriveFont(jLabelCewkaDJdn.getFont().getStyle() | java.awt.Font.BOLD));
        jLabelCewkaDJdn.setText(resourceMap.getString("jLabelCewkaDJdn.text")); // NOI18N
        jLabelCewkaDJdn.setName("jLabelCewkaDJdn"); // NOI18N

        jLabelCewkaNJdn.setFont(jLabelCewkaNJdn.getFont().deriveFont(jLabelCewkaNJdn.getFont().getStyle() | java.awt.Font.BOLD));
        jLabelCewkaNJdn.setText(resourceMap.getString("jLabelCewkaNJdn.text")); // NOI18N
        jLabelCewkaNJdn.setName("jLabelCewkaNJdn"); // NOI18N

        jTextCewkaRs.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextCewkaRs.setText(resourceMap.getString("jTextCewkaRs.text")); // NOI18N
        jTextCewkaRs.setName("jTextCewkaRs"); // NOI18N

        jTextCewkaRs.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(javax.swing.KeyStroke.getKeyStroke("F7"), "F7 pressed");
        jTextCewkaRs.getActionMap().put("F7 pressed", new javax.swing.AbstractAction() {
            public void actionPerformed(ActionEvent evt) {
                cewkaCalc.decRs(false);
                ReflectCewkaCalc();
            }
        });

        jTextCewkaRs.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(javax.swing.KeyStroke.getKeyStroke("shift F7"), "shift F7 pressed");
        jTextCewkaRs.getActionMap().put("shift F7 pressed", new javax.swing.AbstractAction() {
            public void actionPerformed(ActionEvent evt) {
                cewkaCalc.decRs(true);
                ReflectCewkaCalc();
            }
        });

        jTextCewkaRs.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(javax.swing.KeyStroke.getKeyStroke("F8"), "F8 pressed");
        jTextCewkaRs.getActionMap().put("F8 pressed", new javax.swing.AbstractAction() {
            public void actionPerformed(ActionEvent evt) {
                cewkaCalc.incRs(false);
                ReflectCewkaCalc();
            }
        });

        jTextCewkaRs.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(javax.swing.KeyStroke.getKeyStroke("shift F8"), "shift F8 pressed");
        jTextCewkaRs.getActionMap().put("shift F8 pressed", new javax.swing.AbstractAction() {
            public void actionPerformed(ActionEvent evt) {
                cewkaCalc.incRs(true);
                ReflectCewkaCalc();
            }
        });
        jTextCewkaRs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCewkaRsActionPerformed(evt);
            }
        });

        jLabelCewkaRsJdn.setFont(jLabelCewkaRsJdn.getFont().deriveFont(jLabelCewkaRsJdn.getFont().getStyle() | java.awt.Font.BOLD));
        jLabelCewkaRsJdn.setText(resourceMap.getString("jLabelCewkaRsJdn.text")); // NOI18N
        jLabelCewkaRsJdn.setName("jLabelCewkaRsJdn"); // NOI18N

        javax.swing.GroupLayout jPanelCewkaWeLayout = new javax.swing.GroupLayout(jPanelCewkaWe);
        jPanelCewkaWe.setLayout(jPanelCewkaWeLayout);
        jPanelCewkaWeLayout.setHorizontalGroup(
            jPanelCewkaWeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCewkaWeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCewkaWeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCewkaWeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCewkaWeLayout.createSequentialGroup()
                            .addComponent(jLabelCewkaRs)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextCewkaRs, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelCewkaRsJdn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jLabelCewkaDDivX, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelCewkaMaxSr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCewkaWeLayout.createSequentialGroup()
                            .addGroup(jPanelCewkaWeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelCewkaD)
                                .addComponent(jLabelCewkaN)
                                .addComponent(jLabelCewkaX))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanelCewkaWeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSpinnerCewkaN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSpinnerCewkaD, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSpinnerCewkaX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanelCewkaWeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelCewkaNJdn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelCewkaDJdn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelCewkaXJdn, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanelCewkaWeLayout.setVerticalGroup(
            jPanelCewkaWeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCewkaWeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCewkaWeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCewkaX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerCewkaX, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCewkaXJdn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCewkaWeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCewkaD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerCewkaD, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCewkaDJdn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCewkaWeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCewkaN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerCewkaN, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCewkaNJdn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabelCewkaMaxSr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCewkaDDivX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCewkaWeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCewkaRs)
                    .addComponent(jTextCewkaRs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCewkaRsJdn))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanelCewkaWy.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), resourceMap.getString("jPanelCewkaWy.border.title"), 0, 0, resourceMap.getFont("jPanelCewkaWy.border.titleFont"), resourceMap.getColor("jPanelCewkaWy.border.titleColor"))); // NOI18N
        jPanelCewkaWy.setFont(jPanelCewkaWy.getFont().deriveFont(jPanelCewkaWy.getFont().getStyle() | java.awt.Font.BOLD, jPanelCewkaWy.getFont().getSize()+1));
        jPanelCewkaWy.setName("jPanelCewkaWy"); // NOI18N

        jLabelCewkaL.setFont(jLabelCewkaL.getFont().deriveFont(jLabelCewkaL.getFont().getStyle() | java.awt.Font.BOLD, jLabelCewkaL.getFont().getSize()+1));
        jLabelCewkaL.setForeground(resourceMap.getColor("jLabelCewkaL.foreground")); // NOI18N
        jLabelCewkaL.setText(resourceMap.getString("jLabelCewkaL.text")); // NOI18N
        jLabelCewkaL.setName("jLabelCewkaL"); // NOI18N

        jLabelCewkaLMi.setFont(jLabelCewkaLMi.getFont().deriveFont(jLabelCewkaLMi.getFont().getStyle() | java.awt.Font.BOLD, jLabelCewkaLMi.getFont().getSize()+1));
        jLabelCewkaLMi.setForeground(resourceMap.getColor("jLabelCewkaLMi.foreground")); // NOI18N
        jLabelCewkaLMi.setText(resourceMap.getString("jLabelCewkaLMi.text")); // NOI18N
        jLabelCewkaLMi.setName("jLabelCewkaLMi"); // NOI18N

        jLabelCewkaQl.setFont(jLabelCewkaQl.getFont().deriveFont(jLabelCewkaQl.getFont().getStyle() | java.awt.Font.BOLD, jLabelCewkaQl.getFont().getSize()+1));
        jLabelCewkaQl.setForeground(resourceMap.getColor("jLabelCewkaQl.foreground")); // NOI18N
        jLabelCewkaQl.setText(resourceMap.getString("jLabelCewkaQl.text")); // NOI18N
        jLabelCewkaQl.setName("jLabelCewkaQl"); // NOI18N

        javax.swing.GroupLayout jPanelCewkaWyLayout = new javax.swing.GroupLayout(jPanelCewkaWy);
        jPanelCewkaWy.setLayout(jPanelCewkaWyLayout);
        jPanelCewkaWyLayout.setHorizontalGroup(
            jPanelCewkaWyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCewkaWyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCewkaWyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCewkaL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(jLabelCewkaLMi, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(jLabelCewkaQl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelCewkaWyLayout.setVerticalGroup(
            jPanelCewkaWyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCewkaWyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCewkaL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCewkaLMi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCewkaQl)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        jPanelCewkaParam.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), resourceMap.getString("jPanelCewkaParam.border.title"), 0, 0, resourceMap.getFont("jPanelCewkaParam.border.titleFont"))); // NOI18N
        jPanelCewkaParam.setFont(jPanelCewkaParam.getFont().deriveFont(jPanelCewkaParam.getFont().getStyle() | java.awt.Font.BOLD, jPanelCewkaParam.getFont().getSize()+1));
        jPanelCewkaParam.setName("jPanelCewkaParam"); // NOI18N

        jLabelCewkaUw.setFont(jLabelCewkaUw.getFont().deriveFont(jLabelCewkaUw.getFont().getStyle() | java.awt.Font.BOLD));
        jLabelCewkaUw.setText(resourceMap.getString("jLabelCewkaUw.text")); // NOI18N
        jLabelCewkaUw.setName("jLabelCewkaUw"); // NOI18N

        jLabelCewkaFx.setFont(jLabelCewkaFx.getFont().deriveFont(jLabelCewkaFx.getFont().getStyle() | java.awt.Font.BOLD));
        jLabelCewkaFx.setText(resourceMap.getString("jLabelCewkaFx.text")); // NOI18N
        jLabelCewkaFx.setName("jLabelCewkaFx"); // NOI18N

        jLabelCewkaWzor.setFont(jLabelCewkaWzor.getFont().deriveFont(jLabelCewkaWzor.getFont().getStyle() | java.awt.Font.BOLD));
        jLabelCewkaWzor.setText(resourceMap.getString("jLabelCewkaWzor.text")); // NOI18N
        jLabelCewkaWzor.setName("jLabelCewkaWzor"); // NOI18N

        jSpinnerCewkaFx.setModel(new pep.StepCountingSpinnerNumberModel());
        jSpinnerCewkaFx.setEditor(new ModelIndependentSpinnerEditor(jSpinnerCewkaFx));
        jSpinnerCewkaFx.setName("jSpinnerCewkaFx"); // NOI18N
        ((ModelIndependentSpinnerEditor)jSpinnerCewkaFx.getEditor()).getTextField().
        addActionListener(new ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cewkaFxEditActionPerformed(evt);
            }
        });
        jSpinnerCewkaFx.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerCewkaFxStateChanged(evt);
            }
        });

        jLabelCewkaFxJdn.setFont(jLabelCewkaFxJdn.getFont().deriveFont(jLabelCewkaFxJdn.getFont().getStyle() | java.awt.Font.BOLD));
        jLabelCewkaFxJdn.setText(resourceMap.getString("jLabelCewkaFxJdn.text")); // NOI18N
        jLabelCewkaFxJdn.setName("jLabelCewkaFxJdn"); // NOI18N

        jTextCewkaMi.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextCewkaMi.setText(resourceMap.getString("jTextCewkaMi.text")); // NOI18N
        jTextCewkaMi.setName("jTextCewkaMi"); // NOI18N
        jTextCewkaMi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCewkaMiActionPerformed(evt);
            }
        });

        jSeparator2.setName("jSeparator2"); // NOI18N

        javax.swing.GroupLayout jPanelCewkaParamLayout = new javax.swing.GroupLayout(jPanelCewkaParam);
        jPanelCewkaParam.setLayout(jPanelCewkaParamLayout);
        jPanelCewkaParamLayout.setHorizontalGroup(
            jPanelCewkaParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCewkaParamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCewkaParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCewkaParamLayout.createSequentialGroup()
                        .addGroup(jPanelCewkaParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelCewkaUw)
                            .addComponent(jLabelCewkaFx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCewkaParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCewkaParamLayout.createSequentialGroup()
                                .addComponent(jSpinnerCewkaFx, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCewkaFxJdn, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                            .addComponent(jTextCewkaMi, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelCewkaWzor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelCewkaParamLayout.setVerticalGroup(
            jPanelCewkaParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCewkaParamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCewkaParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCewkaUw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCewkaMi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanelCewkaParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCewkaFxJdn)
                    .addComponent(jLabelCewkaFx)
                    .addComponent(jSpinnerCewkaFx, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCewkaWzor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );

        jLabel12.setFont(jLabel12.getFont());
        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        javax.swing.GroupLayout cewkapPanelLayout = new javax.swing.GroupLayout(cewkapPanel);
        cewkapPanel.setLayout(cewkapPanelLayout);
        cewkapPanelLayout.setHorizontalGroup(
            cewkapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cewkapPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cewkapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cewkapPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                    .addGroup(cewkapPanelLayout.createSequentialGroup()
                        .addComponent(jPanelCewkaWe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelCewkaWy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelCewkaParam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE))
                .addContainerGap())
        );
        cewkapPanelLayout.setVerticalGroup(
            cewkapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cewkapPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cewkapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(cewkapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelCewkaWe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCewkaWy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCewkaParam, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        jPanelCewkaWe.getAccessibleContext().setAccessibleName(resourceMap.getString("jPanelCewkaWe.AccessibleContext.accessibleName")); // NOI18N

        calculatorsTPane.addTab(resourceMap.getString("cewkapPanel.TabConstraints.tabTitle"), cewkapPanel); // NOI18N

        lpnPanel.setName("lpnPanel"); // NOI18N

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getStyle() | java.awt.Font.BOLD, jLabel2.getFont().getSize()+3));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel10.setFont(jLabel10.getFont().deriveFont(jLabel10.getFont().getSize()+1f));
        jLabel10.setForeground(resourceMap.getColor("jLabel10.foreground")); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N

        jLabel14.setText(resourceMap.getString("jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N

        jPanelLPNWe.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), resourceMap.getString("jPanelLPNWe.border.title"), 0, 0, resourceMap.getFont("jPanelLPNWe.border.titleFont"), resourceMap.getColor("jPanelLPNWe.border.titleColor"))); // NOI18N
        jPanelLPNWe.setFont(jPanelLPNWe.getFont().deriveFont(jPanelLPNWe.getFont().getStyle() | java.awt.Font.BOLD, jPanelLPNWe.getFont().getSize()+1));
        jPanelLPNWe.setName("jPanelLPNWe"); // NOI18N

        jLabelLPNW.setFont(jLabelLPNW.getFont().deriveFont(jLabelLPNW.getFont().getStyle() | java.awt.Font.BOLD));
        jLabelLPNW.setText(resourceMap.getString("jLabelLPNW.text")); // NOI18N
        jLabelLPNW.setName("jLabelLPNW"); // NOI18N

        jLabelLPNH.setFont(jLabelLPNH.getFont().deriveFont(jLabelLPNH.getFont().getStyle() | java.awt.Font.BOLD));
        jLabelLPNH.setText(resourceMap.getString("jLabelLPNH.text")); // NOI18N
        jLabelLPNH.setName("jLabelLPNH"); // NOI18N

        jSpinnerLPNW.setModel(new StepCountingSpinnerNumberModel());
        jSpinnerLPNW.setEditor(new ModelIndependentSpinnerEditor(jSpinnerLPNW));
        jSpinnerLPNW.setName("jSpinnerLPNW"); // NOI18N

        jSpinnerLPNH.setModel(new StepCountingSpinnerNumberModel());
        jSpinnerLPNH.setEditor(new ModelIndependentSpinnerEditor(jSpinnerLPNH));
        jSpinnerLPNH.setName("jSpinnerLPNH"); // NOI18N

        jSeparator3.setName("jSeparator3"); // NOI18N

        jLabelLPNWJdn.setFont(jLabelLPNWJdn.getFont().deriveFont(jLabelLPNWJdn.getFont().getStyle() | java.awt.Font.BOLD));
        jLabelLPNWJdn.setText(resourceMap.getString("jLabelLPNWJdn.text")); // NOI18N
        jLabelLPNWJdn.setName("jLabelLPNWJdn"); // NOI18N

        jLabelLPNHJdn.setFont(jLabelLPNHJdn.getFont().deriveFont(jLabelLPNHJdn.getFont().getStyle() | java.awt.Font.BOLD));
        jLabelLPNHJdn.setText(resourceMap.getString("jLabelLPNHJdn.text")); // NOI18N
        jLabelLPNHJdn.setName("jLabelLPNHJdn"); // NOI18N

        jLabelLPNWDivH.setFont(jLabelLPNWDivH.getFont().deriveFont(jLabelLPNWDivH.getFont().getStyle() | java.awt.Font.BOLD));
        jLabelLPNWDivH.setText(resourceMap.getString("jLabelLPNWDivH.text")); // NOI18N
        jLabelLPNWDivH.setName("jLabelLPNWDivH"); // NOI18N

        jLabelLPNW_ef.setFont(jLabelLPNW_ef.getFont().deriveFont(jLabelLPNW_ef.getFont().getStyle() | java.awt.Font.BOLD));
        jLabelLPNW_ef.setText(resourceMap.getString("jLabelLPNW_ef.text")); // NOI18N
        jLabelLPNW_ef.setName("jLabelLPNW_ef"); // NOI18N

        jLabelLPNEps_ef.setFont(jLabelLPNEps_ef.getFont().deriveFont(jLabelLPNEps_ef.getFont().getStyle() | java.awt.Font.BOLD));
        jLabelLPNEps_ef.setText(resourceMap.getString("jLabelLPNEps_ef.text")); // NOI18N
        jLabelLPNEps_ef.setName("jLabelLPNEps_ef"); // NOI18N

        jLabelLPNW_mls.setFont(jLabelLPNW_mls.getFont().deriveFont(jLabelLPNW_mls.getFont().getStyle() & ~java.awt.Font.BOLD));
        jLabelLPNW_mls.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelLPNW_mls.setText(resourceMap.getString("jLabelLPNW_mls.text")); // NOI18N
        jLabelLPNW_mls.setName("jLabelLPNW_mls"); // NOI18N

        jLabelLPNW_mlsJdn.setFont(jLabelLPNW_mlsJdn.getFont().deriveFont(jLabelLPNW_mlsJdn.getFont().getStyle() | java.awt.Font.BOLD));
        jLabelLPNW_mlsJdn.setText(resourceMap.getString("jLabelLPNW_mlsJdn.text")); // NOI18N
        jLabelLPNW_mlsJdn.setName("jLabelLPNW_mlsJdn"); // NOI18N

        javax.swing.GroupLayout jPanelLPNWeLayout = new javax.swing.GroupLayout(jPanelLPNWe);
        jPanelLPNWe.setLayout(jPanelLPNWeLayout);
        jPanelLPNWeLayout.setHorizontalGroup(
            jPanelLPNWeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLPNWeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLPNWeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(jLabelLPNWDivH, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(jLabelLPNW_ef, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(jLabelLPNEps_ef, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addGroup(jPanelLPNWeLayout.createSequentialGroup()
                        .addGroup(jPanelLPNWeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLPNWeLayout.createSequentialGroup()
                                .addComponent(jLabelLPNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSpinnerLPNH, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLPNWeLayout.createSequentialGroup()
                                .addComponent(jLabelLPNW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addGroup(jPanelLPNWeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabelLPNW_mls, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinnerLPNW, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))))
                        .addGroup(jPanelLPNWeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLPNWeLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelLPNWJdn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelLPNWeLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabelLPNW_mlsJdn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLPNWeLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabelLPNHJdn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanelLPNWeLayout.setVerticalGroup(
            jPanelLPNWeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLPNWeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLPNWeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerLPNW, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLPNW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLPNWJdn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLPNWeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLPNW_mls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLPNW_mlsJdn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanelLPNWeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerLPNH, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLPNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLPNHJdn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelLPNWDivH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelLPNW_ef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelLPNEps_ef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jLabelLPNW_mlsJdn.getAccessibleContext().setAccessibleName(resourceMap.getString("jLabelLPNW_mlsJdn.AccessibleContext.accessibleName")); // NOI18N

        jPanelLPNWy.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), resourceMap.getString("jPanelLPNWy.border.title"), 0, 0, resourceMap.getFont("jPanelLPNWy.border.titleFont"), resourceMap.getColor("jPanelLPNWy.border.titleColor"))); // NOI18N
        jPanelLPNWy.setEnabled(false);
        jPanelLPNWy.setName("jPanelLPNWy"); // NOI18N

        jLabelLPNZ0.setFont(jLabelLPNZ0.getFont().deriveFont(jLabelLPNZ0.getFont().getStyle() | java.awt.Font.BOLD, jLabelLPNZ0.getFont().getSize()+1));
        jLabelLPNZ0.setForeground(resourceMap.getColor("jLabelLPNZ0.foreground")); // NOI18N
        jLabelLPNZ0.setText(resourceMap.getString("jLabelLPNZ0.text")); // NOI18N
        jLabelLPNZ0.setName("jLabelLPNZ0"); // NOI18N

        javax.swing.GroupLayout jPanelLPNWyLayout = new javax.swing.GroupLayout(jPanelLPNWy);
        jPanelLPNWy.setLayout(jPanelLPNWyLayout);
        jPanelLPNWyLayout.setHorizontalGroup(
            jPanelLPNWyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLPNWyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLPNZ0, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelLPNWyLayout.setVerticalGroup(
            jPanelLPNWyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLPNWyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLPNZ0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        jLabelLPNZ0.getAccessibleContext().setAccessibleName(resourceMap.getString("jLabelLPNZ0.AccessibleContext.accessibleName")); // NOI18N

        jPanelLPNParam.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), resourceMap.getString("jPanelLPNParam.border.title"), 0, 0, resourceMap.getFont("jPanelLPNParam.border.titleFont"))); // NOI18N
        jPanelLPNParam.setEnabled(false);
        jPanelLPNParam.setName("jPanelLPNParam"); // NOI18N

        jLabelLPNT.setFont(jLabelLPNT.getFont().deriveFont(jLabelLPNT.getFont().getStyle() | java.awt.Font.BOLD));
        jLabelLPNT.setText(resourceMap.getString("jLabelLPNT.text")); // NOI18N
        jLabelLPNT.setEnabled(false);
        jLabelLPNT.setName("jLabelLPNT"); // NOI18N

        jLabelLPNEps.setFont(jLabelLPNEps.getFont().deriveFont(jLabelLPNEps.getFont().getStyle() | java.awt.Font.BOLD));
        jLabelLPNEps.setText(resourceMap.getString("jLabelLPNEps.text")); // NOI18N
        jLabelLPNEps.setEnabled(false);
        jLabelLPNEps.setName("jLabelLPNEps"); // NOI18N

        jTextLPNT.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextLPNT.setText(resourceMap.getString("jTextLPNT.text")); // NOI18N
        jTextLPNT.setName("jTextLPNT"); // NOI18N

        jSpinnerLPNEps.setName("jSpinnerLPNEps"); // NOI18N

        jLabelLPNTJdn.setFont(jLabelLPNTJdn.getFont().deriveFont(jLabelLPNTJdn.getFont().getStyle() | java.awt.Font.BOLD));
        jLabelLPNTJdn.setText(resourceMap.getString("jLabelLPNTJdn.text")); // NOI18N
        jLabelLPNTJdn.setName("jLabelLPNTJdn"); // NOI18N

        javax.swing.GroupLayout jPanelLPNParamLayout = new javax.swing.GroupLayout(jPanelLPNParam);
        jPanelLPNParam.setLayout(jPanelLPNParamLayout);
        jPanelLPNParamLayout.setHorizontalGroup(
            jPanelLPNParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLPNParamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLPNParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLPNParamLayout.createSequentialGroup()
                        .addComponent(jLabelLPNT, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextLPNT, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelLPNTJdn, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                    .addGroup(jPanelLPNParamLayout.createSequentialGroup()
                        .addComponent(jLabelLPNEps, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerLPNEps, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelLPNParamLayout.setVerticalGroup(
            jPanelLPNParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLPNParamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLPNParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLPNT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextLPNT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLPNTJdn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLPNParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLPNEps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerLPNEps, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        jTextLPNT.getAccessibleContext().setAccessibleName(resourceMap.getString("jTextLPNT.AccessibleContext.accessibleName")); // NOI18N
        jSpinnerLPNEps.getAccessibleContext().setAccessibleName(resourceMap.getString("jSpinnerLPNEps.AccessibleContext.accessibleName")); // NOI18N

        jLabel18.setFont(jLabel18.getFont());
        jLabel18.setForeground(resourceMap.getColor("jLabel18.foreground")); // NOI18N
        jLabel18.setText(resourceMap.getString("jLabel18.text")); // NOI18N
        jLabel18.setName("jLabel18"); // NOI18N

        javax.swing.GroupLayout lpnPanelLayout = new javax.swing.GroupLayout(lpnPanel);
        lpnPanel.setLayout(lpnPanelLayout);
        lpnPanelLayout.setHorizontalGroup(
            lpnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lpnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lpnPanelLayout.createSequentialGroup()
                        .addComponent(jPanelLPNWe, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelLPNWy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelLPNParam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lpnPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(186, 186, 186)
                        .addComponent(jLabel5))
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE))
                .addContainerGap())
        );
        lpnPanelLayout.setVerticalGroup(
            lpnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lpnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(lpnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelLPNParam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelLPNWy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelLPNWe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel14)
                .addContainerGap())
        );

        jPanelLPNWe.getAccessibleContext().setAccessibleName(resourceMap.getString("jPanel1.AccessibleContext.accessibleName")); // NOI18N
        jPanelLPNWy.getAccessibleContext().setAccessibleName(resourceMap.getString("jPanel1.AccessibleContext.accessibleName")); // NOI18N
        jPanelLPNParam.getAccessibleContext().setAccessibleName(resourceMap.getString("jPanel1.AccessibleContext.accessibleName")); // NOI18N

        calculatorsTPane.addTab(resourceMap.getString("lpnPanel.TabConstraints.tabTitle"), lpnPanel); // NOI18N

        rezPanel.setName("rezPanel"); // NOI18N

        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getStyle() | java.awt.Font.BOLD, jLabel3.getFont().getSize()+3));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setEnabled(false);
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setEnabled(false);
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel11.setFont(jLabel11.getFont().deriveFont(jLabel11.getFont().getSize()+1f));
        jLabel11.setForeground(resourceMap.getColor("jLabel11.foreground")); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setEnabled(false);
        jLabel11.setName("jLabel11"); // NOI18N

        jLabel15.setText(resourceMap.getString("jLabel15.text")); // NOI18N
        jLabel15.setEnabled(false);
        jLabel15.setName("jLabel15"); // NOI18N

        jLabel16.setText(resourceMap.getString("jLabel16.text")); // NOI18N
        jLabel16.setEnabled(false);
        jLabel16.setName("jLabel16"); // NOI18N

        jPanelRezonWe.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), resourceMap.getString("jPanelRezonWe.border.title"), 0, 0, resourceMap.getFont("jPanelRezonWe.border.titleFont"), resourceMap.getColor("jPanelRezonWe.border.titleColor"))); // NOI18N
        jPanelRezonWe.setEnabled(false);
        jPanelRezonWe.setName("jPanelRezonWe"); // NOI18N

        javax.swing.GroupLayout jPanelRezonWeLayout = new javax.swing.GroupLayout(jPanelRezonWe);
        jPanelRezonWe.setLayout(jPanelRezonWeLayout);
        jPanelRezonWeLayout.setHorizontalGroup(
            jPanelRezonWeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 209, Short.MAX_VALUE)
        );
        jPanelRezonWeLayout.setVerticalGroup(
            jPanelRezonWeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 211, Short.MAX_VALUE)
        );

        jPanelRezonWy.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), resourceMap.getString("jPanelRezonWy.border.title"), 0, 0, resourceMap.getFont("jPanelRezonWy.border.titleFont"), resourceMap.getColor("jPanelRezonWy.border.titleColor"))); // NOI18N
        jPanelRezonWy.setEnabled(false);
        jPanelRezonWy.setName("jPanelRezonWy"); // NOI18N

        javax.swing.GroupLayout jPanelRezonWyLayout = new javax.swing.GroupLayout(jPanelRezonWy);
        jPanelRezonWy.setLayout(jPanelRezonWyLayout);
        jPanelRezonWyLayout.setHorizontalGroup(
            jPanelRezonWyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
        );
        jPanelRezonWyLayout.setVerticalGroup(
            jPanelRezonWyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 211, Short.MAX_VALUE)
        );

        jPanelRezonParam.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), resourceMap.getString("jPanelRezonParam.border.title"), 0, 0, resourceMap.getFont("jPanelRezonParam.border.titleFont"))); // NOI18N
        jPanelRezonParam.setEnabled(false);
        jPanelRezonParam.setName("jPanelRezonParam"); // NOI18N

        javax.swing.GroupLayout jPanelRezonParamLayout = new javax.swing.GroupLayout(jPanelRezonParam);
        jPanelRezonParam.setLayout(jPanelRezonParamLayout);
        jPanelRezonParamLayout.setHorizontalGroup(
            jPanelRezonParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 205, Short.MAX_VALUE)
        );
        jPanelRezonParamLayout.setVerticalGroup(
            jPanelRezonParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 211, Short.MAX_VALUE)
        );

        jLabel19.setFont(jLabel19.getFont().deriveFont(jLabel19.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel19.setForeground(resourceMap.getColor("jLabel19.foreground")); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText(resourceMap.getString("jLabel19.text")); // NOI18N
        jLabel19.setName("jLabel19"); // NOI18N

        javax.swing.GroupLayout rezPanelLayout = new javax.swing.GroupLayout(rezPanel);
        rezPanel.setLayout(rezPanelLayout);
        rezPanelLayout.setHorizontalGroup(
            rezPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rezPanelLayout.createSequentialGroup()
                .addGroup(rezPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rezPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE))
                    .addGroup(rezPanelLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                        .addGap(102, 102, 102)
                        .addComponent(jLabel6))
                    .addGroup(rezPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE))
                    .addGroup(rezPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelRezonWe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelRezonWy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelRezonParam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(rezPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE))
                    .addGroup(rezPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)))
                .addContainerGap())
        );
        rezPanelLayout.setVerticalGroup(
            rezPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rezPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rezPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(rezPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelRezonParam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelRezonWy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelRezonWe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addContainerGap())
        );

        jPanelRezonWe.getAccessibleContext().setAccessibleName(resourceMap.getString("jPanel1.AccessibleContext.accessibleName")); // NOI18N
        jPanelRezonWy.getAccessibleContext().setAccessibleName(resourceMap.getString("jPanel2.AccessibleContext.accessibleName")); // NOI18N
        jPanelRezonParam.getAccessibleContext().setAccessibleName(resourceMap.getString("jPanel3.AccessibleContext.accessibleName")); // NOI18N

        calculatorsTPane.addTab(resourceMap.getString("rezPanel.TabConstraints.tabTitle"), rezPanel); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(calculatorsTPane, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(calculatorsTPane, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
        );

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        jMenuItemOtworz.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemOtworz.setText(resourceMap.getString("jMenuItemOtworz.text")); // NOI18N
        jMenuItemOtworz.setEnabled(false);
        jMenuItemOtworz.setName("jMenuItemOtworz"); // NOI18N
        fileMenu.add(jMenuItemOtworz);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(pep.PEPApp.class).getContext().getActionMap(PEPView.class, this);
        jMenuItemZapisz.setAction(actionMap.get("saveDefaultParamFile")); // NOI18N
        jMenuItemZapisz.setText(resourceMap.getString("jMenuItemZapisz.text")); // NOI18N
        jMenuItemZapisz.setToolTipText(resourceMap.getString("jMenuItemZapisz.toolTipText")); // NOI18N
        jMenuItemZapisz.setName("jMenuItemZapisz"); // NOI18N
        fileMenu.add(jMenuItemZapisz);

        jMenuItemZapiszJako.setText(resourceMap.getString("jMenuItemZapiszJako.text")); // NOI18N
        jMenuItemZapiszJako.setEnabled(false);
        jMenuItemZapiszJako.setName("jMenuItemZapiszJako"); // NOI18N
        fileMenu.add(jMenuItemZapiszJako);

        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setText(resourceMap.getString("exitMenuItem.text")); // NOI18N
        exitMenuItem.setToolTipText(resourceMap.getString("exitMenuItem.toolTipText")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setText(resourceMap.getString("aboutMenuItem.text")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setComponent(mainPanel);
        setMenuBar(menuBar);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        saveDefaultParamFile();
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void jSpinnerCewkaXStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerCewkaXStateChanged
        Integer c = (Integer)((StepCountingSpinnerNumberModel)jSpinnerCewkaX.getModel()).getValue();
        Integer p = (Integer)((StepCountingSpinnerNumberModel)jSpinnerCewkaX.getModel()).getHistory();
        
        if (c < p)
            cewkaCalc.decX(false);
        else /*if(p > c)*/
            cewkaCalc.incX(false);
        
        ReflectCewkaCalc();
    }//GEN-LAST:event_jSpinnerCewkaXStateChanged

    private void jSpinnerCewkaDStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerCewkaDStateChanged
        Integer c = (Integer)((StepCountingSpinnerNumberModel)jSpinnerCewkaD.getModel()).getValue();
        Integer p = (Integer)((StepCountingSpinnerNumberModel)jSpinnerCewkaD.getModel()).getHistory();
        
        if (c < p)
            cewkaCalc.decD(false);
        else /*if(p > c)*/
            cewkaCalc.incD(false);
        
        ReflectCewkaCalc();
    }//GEN-LAST:event_jSpinnerCewkaDStateChanged

    private void jSpinnerCewkaNStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerCewkaNStateChanged
        Integer c = (Integer)((StepCountingSpinnerNumberModel)jSpinnerCewkaN.getModel()).getValue();
        Integer p = (Integer)((StepCountingSpinnerNumberModel)jSpinnerCewkaN.getModel()).getHistory();
        
        if (c < p)
            cewkaCalc.decN(false);
        else /*if(p > c)*/
            cewkaCalc.incN(false);
        
        ReflectCewkaCalc();
    }//GEN-LAST:event_jSpinnerCewkaNStateChanged

    private void jSpinnerCewkaFxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerCewkaFxStateChanged
        Integer c = (Integer)((StepCountingSpinnerNumberModel)jSpinnerCewkaFx.getModel()).getValue();
        Integer p = (Integer)((StepCountingSpinnerNumberModel)jSpinnerCewkaFx.getModel()).getHistory();
        
        if (c < p)
            cewkaCalc.decFx();
        else /*if(p > c)*/
            cewkaCalc.incFx();

        ReflectCewkaCalc();
    }//GEN-LAST:event_jSpinnerCewkaFxStateChanged

    private void cewkaXEditActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            double val = pepCalculator.Norm.GetValueFromString(evt.getActionCommand());
            cewkaCalc.setX(val * 1000.);
            ReflectCewkaCalc();
        }
        catch (NumberFormatException nfe) {
            ReflectCewkaCalc();
        }        
    }

    private void cewkaDEditActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            double val = pepCalculator.Norm.GetValueFromString(evt.getActionCommand());
            cewkaCalc.setD(val * 1000.);
            ReflectCewkaCalc();
        }
        catch (NumberFormatException nfe) {
            ReflectCewkaCalc();
        }        
    }

    private void cewkaNEditActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            double val = pepCalculator.Norm.GetValueFromString(evt.getActionCommand());
            cewkaCalc.setN(val);
            ReflectCewkaCalc();
        }
        catch (NumberFormatException nfe) {
            ReflectCewkaCalc();
        }        
    }

    private void jTextCewkaMiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCewkaMiActionPerformed
        try {
            double val = pepCalculator.Norm.GetValueFromString(jTextCewkaMi.getText());
            cewkaCalc.setMi(val);
            ReflectCewkaCalc();
        }
        catch (NumberFormatException nfe) {
            ReflectCewkaCalc();
        }
    }//GEN-LAST:event_jTextCewkaMiActionPerformed

    private void cewkaFxEditActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            double val = pepCalculator.Norm.GetValueFromString(evt.getActionCommand());
            cewkaCalc.setFx(val);
            ReflectCewkaCalc();
        }
        catch (NumberFormatException nfe) {
            ReflectCewkaCalc();
        }
    }
    
    private void jTextCewkaRsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCewkaRsActionPerformed
        try {
            double val = pepCalculator.Norm.GetValueFromString(jTextCewkaRs.getText());
            cewkaCalc.setRs(val);
            ReflectCewkaCalc();            
        }
        catch (NumberFormatException nfe) {
            ReflectCewkaCalc();
        }
    }//GEN-LAST:event_jTextCewkaRsActionPerformed

    private void initCalcs()
    {
        InitCewkaKalk();
        InitLPNKalk();
        InitRezonKalk();
    }
    
    private void reflectCalcs()
    {
        ReflectCewkaCalc();
        ReflectLPNCalc();
        ReflectRezonKalk();
    }
    
    private void InitCewkaKalk()
    {
        cewkaCalc = new pepCalculator.CewkaP();
//        cewkaKalk.AfterAny();
//        ReflectCewkaKalk();
    }
    
    private void InitLPNKalk()
    {
        LPNCalc = new pepCalculator.LPN();
    }
    
    private void InitRezonKalk()
    {
    }
    
    private void ReflectCewkaCalc()
    {
        cewkaCalc.AfterAny();

        // WEJSCIE
        double X = cewkaCalc.getX() / 1000.;
        double D = cewkaCalc.getD() / 1000.;
        double N = cewkaCalc.getN();

        pepCalculator.DisplayValue XNorm = pepCalculator.Norm.GetDispVal(X);
        pepCalculator.DisplayValue DNorm = pepCalculator.Norm.GetDispVal(D);
        pepCalculator.DisplayValue XDivNNorm = pepCalculator.Norm.GetDispVal(X/N);
        pepCalculator.DisplayValue RsNorm = pepCalculator.Norm.GetDispVal(cewkaCalc.getRs());
        
        ((ModelIndependentSpinnerEditor)jSpinnerCewkaX.getEditor()).setText(((Double)XNorm.GetVal()).toString());
        jLabelCewkaXJdn.setText("<html><b>[" + XNorm.GetSym() + "m]</b>");
        ((ModelIndependentSpinnerEditor)jSpinnerCewkaD.getEditor()).setText(((Double)DNorm.GetVal()).toString());
        jLabelCewkaDJdn.setText("<html><b>[" + DNorm.GetSym() + "m]</b>");
        ((ModelIndependentSpinnerEditor)jSpinnerCewkaN.getEditor()).setText(((Double)N).toString());
        jLabelCewkaMaxSr.setText("<html><b>max. sr. drutu: " + XDivNNorm.GetVal() + " [" + XDivNNorm.GetSym() + "m]</b>");
        jLabelCewkaDDivX.setText("<html><b>D/X = " + D/X + "</b>");
        jTextCewkaRs.setText(((Double)RsNorm.GetVal()).toString());
        jLabelCewkaRsJdn.setText("<html><b>[" + RsNorm.GetSym() + "\u03a9]</b>");
        
        // WYJSCIE
        pepCalculator.DisplayValue LNorm = pepCalculator.Norm.GetDispVal(cewkaCalc.getLx());
        pepCalculator.DisplayValue LuNorm = pepCalculator.Norm.GetDispVal(cewkaCalc.getLmi());
        
        jLabelCewkaL.setText("<html><b>L &#32= " + LNorm.GetVal() + " [" + LNorm.GetSym() + "H]</b>");
        jLabelCewkaLMi.setText("<html><b>L\u03bc = " + LuNorm.GetVal() + " [" + LuNorm.GetSym() + "H]</b>");
        jLabelCewkaQl.setText("<html><b>Ql = " + pepCalculator.Norm.Round(cewkaCalc.getQl(), 3) + "</b>");

        // PARAMETRY
        pepCalculator.DisplayValue FxNorm = pepCalculator.Norm.GetDispVal(cewkaCalc.getFx());
        
        jLabelCewkaFxJdn.setText("<html><b>[" + FxNorm.GetSym() + "Hz]</b>");
        jTextCewkaMi.setText(((Double)cewkaCalc.getMi()).toString());
        jLabelCewkaWzor.setText(cewkaCalc.getWylKom());
        
        ((ModelIndependentSpinnerEditor)jSpinnerCewkaFx.getEditor()).setText(((Double)FxNorm.GetVal()).toString());
    }
    
    private void ReflectLPNCalc()
    {
        LPNCalc.AfterAny();
        
        // WEJSCIE
        double W = LPNCalc.getW() / 1000.;
        int W_mls = LPNCalc.getW_mls();
        double H = LPNCalc.getH() / 1000.;
        double W_ef = LPNCalc.getW_ef() / 1000.;
        double Eps_ef = LPNCalc.getEps_ef();
        
        pepCalculator.DisplayValue WNorm = pepCalculator.Norm.GetDispVal(W);
        pepCalculator.DisplayValue HNorm = pepCalculator.Norm.GetDispVal(H);
        pepCalculator.DisplayValue W_efNorm = pepCalculator.Norm.GetDispVal(W_ef);
        pepCalculator.DisplayValue Eps_efNorm = pepCalculator.Norm.GetDispVal(Eps_ef);
        
        ((ModelIndependentSpinnerEditor)jSpinnerLPNW.getEditor()).setText(((Double)WNorm.GetVal()).toString());
        jLabelLPNWJdn.setText("<html><b>[" + WNorm.GetSym() + "m]</b>");
//        jLabelLPNW_mls.setText("<html><b>" + W_mls + "</b>");
        jLabelLPNW_mls.setText("<html>" + W_mls);
        jLabelLPNW_mlsJdn.setText("<html><b>[mls]</b>");
        ((ModelIndependentSpinnerEditor)jSpinnerLPNH.getEditor()).setText(((Double)HNorm.GetVal()).toString());
        jLabelLPNHJdn.setText("<html><b>[" + HNorm.GetSym() + "m]</b>");
        jLabelLPNWDivH.setText("<html><b>D/X = " + W/H + "</b>");
        jLabelLPNW_ef.setText("<html><b>W_ef = " + W_efNorm.GetVal() + " [" + W_efNorm.GetSym() + "m]</b>");
        jLabelLPNEps_ef.setText("<html><b>&#949_ef = " + Eps_efNorm.GetVal() + " [" +  Eps_efNorm.GetSym() + "]</b>");
        
        // WYJSCIE
        pepCalculator.DisplayValue Z0Norm = pepCalculator.Norm.GetDispVal(LPNCalc.getZ0());
        
        jLabelLPNZ0.setText("<html><b>Z<sub>0</sub> = " + Z0Norm.GetVal() + " [" + Z0Norm.GetSym() + "\u03a9]</b>");
        
        // PARAMETRY
    }
    
    private void ReflectRezonKalk()
    {
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane calculatorsTPane;
    private javax.swing.JPanel cewkapPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCewkaD;
    private javax.swing.JLabel jLabelCewkaDDivX;
    private javax.swing.JLabel jLabelCewkaDJdn;
    private javax.swing.JLabel jLabelCewkaFx;
    private javax.swing.JLabel jLabelCewkaFxJdn;
    private javax.swing.JLabel jLabelCewkaL;
    private javax.swing.JLabel jLabelCewkaLMi;
    private javax.swing.JLabel jLabelCewkaMaxSr;
    private javax.swing.JLabel jLabelCewkaN;
    private javax.swing.JLabel jLabelCewkaNJdn;
    private javax.swing.JLabel jLabelCewkaQl;
    private javax.swing.JLabel jLabelCewkaRs;
    private javax.swing.JLabel jLabelCewkaRsJdn;
    private javax.swing.JLabel jLabelCewkaUw;
    private javax.swing.JLabel jLabelCewkaWzor;
    private javax.swing.JLabel jLabelCewkaX;
    private javax.swing.JLabel jLabelCewkaXJdn;
    private javax.swing.JLabel jLabelLPNEps;
    private javax.swing.JLabel jLabelLPNEps_ef;
    private javax.swing.JLabel jLabelLPNH;
    private javax.swing.JLabel jLabelLPNHJdn;
    private javax.swing.JLabel jLabelLPNT;
    private javax.swing.JLabel jLabelLPNTJdn;
    private javax.swing.JLabel jLabelLPNW;
    private javax.swing.JLabel jLabelLPNWDivH;
    private javax.swing.JLabel jLabelLPNWJdn;
    private javax.swing.JLabel jLabelLPNW_ef;
    private javax.swing.JLabel jLabelLPNW_mls;
    private javax.swing.JLabel jLabelLPNW_mlsJdn;
    private javax.swing.JLabel jLabelLPNZ0;
    private javax.swing.JMenuItem jMenuItemOtworz;
    private javax.swing.JMenuItem jMenuItemZapisz;
    private javax.swing.JMenuItem jMenuItemZapiszJako;
    private javax.swing.JPanel jPanelCewkaParam;
    private javax.swing.JPanel jPanelCewkaWe;
    private javax.swing.JPanel jPanelCewkaWy;
    private javax.swing.JPanel jPanelLPNParam;
    private javax.swing.JPanel jPanelLPNWe;
    private javax.swing.JPanel jPanelLPNWy;
    private javax.swing.JPanel jPanelRezonParam;
    private javax.swing.JPanel jPanelRezonWe;
    private javax.swing.JPanel jPanelRezonWy;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSpinner jSpinnerCewkaD;
    private javax.swing.JSpinner jSpinnerCewkaFx;
    private javax.swing.JSpinner jSpinnerCewkaN;
    private javax.swing.JSpinner jSpinnerCewkaX;
    private javax.swing.JSpinner jSpinnerLPNEps;
    private javax.swing.JSpinner jSpinnerLPNH;
    private javax.swing.JSpinner jSpinnerLPNW;
    private javax.swing.JTextField jTextCewkaMi;
    private javax.swing.JTextField jTextCewkaRs;
    private javax.swing.JTextField jTextLPNT;
    private javax.swing.JPanel lpnPanel;
    public javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel rezPanel;
    // End of variables declaration//GEN-END:variables

    private pepCalculator.CewkaP cewkaCalc;
    private pepCalculator.LPN LPNCalc;
    
    private final Timer messageTimer;
    private final Timer busyIconTimer;
    private final Icon idleIcon;
    private final Icon[] busyIcons = new Icon[15];
    private int busyIconIndex = 0;

    private JDialog aboutBox;
}
